---
Apps:
    Amazon:             com.amazon.mShop.android
    Boost:              com.tct.onetouchbooster
    Browser:            com.android.browser
    Calculator:         com.tct.calculator
    Calendar:           com.google.android.calendar
    Call:               com.android.dialer
    Camera:             com.tct.camera
    Candy Crush Jelly:  com.king.candycrushjellysaga
    Chrome:             com.android.chrome
    Clock:              com.google.android.deskclock
    Compass:            com.jrdcom.compass
    Contacts:           com.android.contacts
    Cookie Jam:         air.com.sgn.cookiejam.gp
    Cricket Rewards:    com.cricketwireless.cricketrewards
    Deezer:             deezer.android.app
    Downloads:          com.android.documentsui
    Drive:              com.google.android.apps.docs
    Email:              com.tct.email
    Farm Heroes Saga:   com.king.farmheroessaga
    Feedback:           com.tct.endusertest
    Files:              com.jrdcom.filemanager
    Fyuse:              com.fyusion.miniSocial
    Gallery:            com.tct.gallery3d
    Gmail:              com.google.android.gm
    Go Security:        com.jb.security
    Google:             com.google.android.googlequicksearchbox
    Google+:            com.google.android.apps.plus
    Hangouts:           com.google.android.talk
    Juice Jam:          air.com.sgn.juicejam.gp
    Keep:               com.google.android.keep
    Littlstar:          com.littlstar.android
    Maps:               com.google.android.apps.maps
    Messaging:          com.android.mms
    Music:              com.alcatel.music5
    myCricket:          com.mizmowireless.acctmgt
    News & Weather:     com.google.android.apps.genie.geniewidget
    Panda Pop:          com.sgn.pandapop.gp
    Pet Rescue Saga:    com.king.petrescuesaga
    Photos:             com.google.android.apps.photos
    Play Books:         com.google.android.apps.books
    Play Games:         com.google.android.play.games
    Play Movies & TV:   com.google.android.videos
    Play Music:         com.google.android.music
    Play Newsstand:     com.google.android.apps.magazines
    Play Store:         com.android.vending
    PSafe Total:        com.psafe.msuite
    Radio:              com.tct.fmradio
    Safe Guard:         com.jrdcom.jrdlogger
    Settings:           com.android.settings
    Shazam:             com.shazam.android
    ShellMS:            com.android.shellms
    Sound Recorder:     com.tct.soundrecorder
    TiZR Lifecasting:   com.app_tizr.app
    Updates:            com.tcl.ota
    Visual Voicemail:   com.mizmowireless.vvm
    Voice Search:       com.google.android.googlequicksearchbox
    VR Hub:             com.nibiru.tcl.vrstore
    VR Launcher:        com.nibiru.tcl.launcher
    VR Store:           com.nibiru.tcl.vrstore
    Waves MaxxAudio:    com.waves.maxxaudio
    Weather:            com.tct.weather
    WhatsApp:           com.whatsapp
    Wi-Fi Display:      com.android.settings
    WPS Office:         cn.wps.moffice_eng
    YouTube:            com.google.android.youtube

IgnoreList:
    clean_master:       Clean Master
    candy_crush_jelly:  Candy Crush Jelly
    cookie_jam:         Cookie Jam
    empire:             Empire
    farm_heroes_saga:   Farm Heroes Saga
    game_of_war:        Game of War
    genies_gems:        Genies & Gems
    juice_jam:          Juice Jam
    mobile_strike:      Mobile Strike
    panda_pop:          Panda Pop
    pet_rescue_saga:    Pet Rescue Saga
    sim_toolkit:        SIM Toolkit
    asphalt0:           Asphalt 0
    smart_suite:        Smart Suite
